language: node_js
node_js:
  - "node"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli@1.2.7
  - npm install -g gh-pages
script:
  - npm install
  - ng build --prod --base-href /fcc-voting-app/
after_success:
 - git config --global user.name "Miguel S. Mendoza"
 - git config --global user.email "[email protected]"
 - git remote rm origin
 - git remote add origin https://MiguelSMendoza:${GH_TOKEN}@github.com/MiguelSMendoza/fcc-voting-app.git
 - npm run deploy
notifications:
  email:
    on_failure: miguel@smendoza.net
    on_success: miguel@smendoza.net